language: node_js

sudo: required
services:
  - docker

install: true

script:
  - docker build -t kamu:base .
  - docker build -t kamu:test -f Dockerfile.test .
  - docker run kamu:test

after_script:
  - ./publish_image.sh
