---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kamu
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
  revisionHistoryLimit: 1
  template:
    metadata:
      labels:
        app: kamu
        env: prod
    spec:
      containers:
      - name: kamu
        # rendered by kube-deploy
        image: {{.Image}}
        resources:
          requests:
            memory: "1.0Gi"
            cpu: "1000m"
          limits:
            memory: "1.0Gi"
            cpu: "1000m"
        ports:
          - containerPort: 8081
            name: http
        readinessProbe:
          httpGet:
            path: "/status"
            port: 8081
          initialDelaySeconds: 5
        env:
          - name: KAMU_KEY
            valueFrom:
              secretKeyRef:
                name: kamu
                key: kamu_key
          - name: KAMU_HOST
            value: ""
          - name: KAMU_PORT
            value: "8081"
---
apiVersion: v1
kind: Service
metadata:
  name: kamu
spec:
  type: NodePort
  ports:
    - port: 31842
      nodePort: 31842 # this is the port ELB should be pointed at
      targetPort: http
      protocol: TCP
  selector:
    app: kamu
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kamu
spec:
  targetCPUUtilizationPercentage: 40
  minReplicas: 20
  maxReplicas: 50
  scaleTargetRef:
    apiVersion: autoscaling/v1
    kind: Deployment
    name: kamu

